###
GET http://localhost:4001/contactservice/

###
GET http://localhost:4001/contactservice/9090909094

###
DELETE http://localhost:4001/contactservice/9090909093

###
POST http://localhost:4001/contactservice
Content-Type: application/json

{
        "phone": 9090909093,
        "name": "joydip",
        "email": "JOYDIP@GMAIL.COM"
}

###
PUT http://localhost:4001/contactservice
Content-Type: application/json

{
        "phone": 9090909094,
        "name": "ramnath nishad",
        "email": "RAMNATH@GMAIL.COM"
}